services:
  web-app:
    image: places-web-app-image:latest
    container_name: places-web-app
    hostname: places-web-app
    # env_file:
    #   - ./config/.env.pre
    build:
      context: ./src/places-web-app
      dockerfile: Dockerfile
      args:
        NODE_ENV: pre
    ports:
      - "4000:80"
    environment:
      - NODE_ENV=production
    networks:
      - places-network

  back-end:
    image: places-back-end-image:latest
    container_name: places-back-end
    hostname: places-back-end
    env_file:
      - ./config/.env.pre
    build:
      context: ./src/demo
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - db-server
    networks:
      - places-network

  db-server:
    image: mcr.microsoft.com/mssql/server:2025-latest
    hostname: places-db-server
    container_name: places-db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
      - MSSQL_PID=Evaluation
    ports:
      - "1433:1433"
    networks:
      - places-network
    volumes:
      - places-db-data:/var/opt/mssql
      # - places-db-data:/var/opt/mssql/data



networks:
  places-network:
    driver: bridge


volumes:
  places-db-data:
    driver: local