spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${DB_SERVER_URL}
    username: ${DB_SERVER_USERNAME}
    password: ${DB_SERVER_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    smtp:
      auth: true
    properties:
      mail:
        smtp:
          ssl:
            enable: true

server:
  servlet:
    context-path: /api

twilio:
  config:
    account_sid: ${TWILIO_ACCOUNT_SID}
    auth_token: ${TWILIO_AUTH_TOKEN}
    from_number: ${TWILIO_FROM_NUMBER}

places_app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refresh_expiration: ${JWT_REFRESH_EXPIRATION}
  email:
    verificacion:
      url: ${EMAIL_VERIFICATION_URL}
      max_attempts: ${EMAIL_VERIFICATION_MAX_ATTEMPTS}
      expiration: ${EMAIL_VERIFICATION_EXPIRATION}
  sms:
    expiration: ${SMS_VERIFICATION_EXPIRATION}
    max_attempts: ${SMS_VERIFICATION_MAX_ATTEMPTS}