spring.application.name=demo

server.servlet.context-path=/api

spring.datasource.url=${SERVER_URL}
spring.datasource.username=${SERVER_USERNAME}
spring.datasource.password=${SERVER_PASSWORD}


# Esta configuración es para que imprima los SQL (queries) generados
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


places_app.jwt.secret=mi_clave_secreta_para_jwt%$_sdfsdlfksjdflksdjflksdfsdsldfk
places_app.jwt.expiration=3600
places_app.jwt.refresh_expiration=4000